### PR TITLE
 A little of irrrrrrrrrradiation never hurts

### PR DESCRIPTION
**Pull request by reoseah**
two item icons, but the second is just a nugget of the first...

### CODE REVIEW

**Comment by reoseah** [comment]
it needs recipes & generation in world, but i'm lazy to do that

**Comment by reoseah** [comment]
also renamed `texures/blocks` to `textures/block` as in modern minecraft resources... effectively disabled Chocohead PR by moving his files

**Comment by reoseah** [comment]
oops, that wasn't meant to be added here

**Comment by reoseah** [comment]
I don't really know how git works
ihave

**Comment by ghost** [comment]
Grr

**Comment by ghost** [comment]
@InsomniaKitten @Shnupbups Review? On mobile rn, so can’t assign reviewers

**Review by Shnupbups — CHANGES_REQUESTED** [review]
Looks good to me, though moving chocohead's files means MixinConfig should be edited to reflect their new locations.

**Comment by reoseah** [comment]
Should work now (or don't as it crashes for me because git have broken png files)

**Review by ChloeDawn — CHANGES_REQUESTED** [review]
Moving Chocohead's textures is out of the scope of this pull request. I understand that they are in the "wrong" directory, but moving them requires updating [their references in MixinConfig](https://github.com/FabricCommunity/community-mod-maybe/blob/cfef4aa37502d582885820a2509372492c61d73a/src/main/java/communitymod/MixinConfig.java#L37-L38) too, which IMO this PR should not be editing. So I would suggest leaving the files where they are, and their location can be fixed later on.

**Comment by ghost** [comment]
@Reoseah Join us on Discord and I can step you through the process: https://discord.gg/v6v4pMv

My tag is `Ibby#7349`

**Comment by reoseah** [comment]
Crashes for me, which means, albeit a little paradoxically, that everything works as expected and worked before!

**Comment by reoseah** [comment]
Now the masterpiece is complete for this week. 

Beware of the glowing green mist in deep caverns, it awaits you! *evil laughter*

**Comment by reoseah** [comment]
Well there are now 4 classes for uranium ore, but they are part of one feature and so should fall under 
> If you feel a single addition would be best suited to multiple files (BlockEntities for example), you may request permission to do so.

Can't say more as that will break
> Keep Pull Requests and commits as vague as possible. Again, others need to figure out your code.

**Comment by Reoseah** [comment]
Now I've probably broke rule...
> Keep Pull Requests and commits as vague as possible. Again, others need to figure out your code.

**Pull request merged**
