### PR TITLE
Extend the rules

### PR DESCRIPTION
**Pull request by Chocohead**
One man's massive class is another man's detailed texture

### CODE REVIEW

**Review by modmuss50 — COMMENTED** [review]
I can neither approve or deny this PR.

**Comment by asiekierka** [comment]
I was waiting for this, no joke

**Comment by shedaniel** [comment]
This is the best item mod

**Review by ChloeDawn — APPROVED** [review]

**Comment by shedaniel** [comment]
I wonder what is hidden

**Comment by ChloeDawn** [comment]
This pull request does not break any of the rules and is prime for merge 🚀

**Review by liach — APPROVED** [review]

**Comment by shedaniel** [comment]
I still don't know what this code do lol

**Comment by Shnupbups** [comment]
I'm not gonna lie, I'm not entirely sure what this code does either, but judging by the mere fact that there's a class named 'LoopHoleHandler', I think it _might_ violate rule 14 (in that it is an attempt to circumvent rules), and thus have to be rejected. (or, in this case, reverted)

I won't do it myself as, again, I'm still not sure what this _does_ in fact do... but if someone could maybe... take another look at it?

**Comment by asiekierka** [comment]
>(or, in this case, reverted)

Which rule says anything about reverting? :thinking:

**Comment by ChloeDawn** [comment]
There is not one massive class that does everything, there are 3 classes that have designated purposes. And there is no overuse of internal classes, they are all top-level classes.

**Comment by Shnupbups** [comment]
> There is not one massive class that does everything, there are 3 classes that have designated purposes. And there is no overuse of internal classes, they are all top-level classes.

The rule is clearly worded so that those are examples of possible circumventions covered by the rule, not a list. Not the use of _such as_.
"Attempts to circumvent these rules through means _such as_..."

Therefore it still falls under it. (Also, when I was writing the rules, I intended for 'internal classes' to just mean several classes in the same file. I'll make the rule more clear.)



> > (or, in this case, reverted)
> 
> Which rule says anything about reverting?

I think if a PR has been merged that shouldn't have been, it should be fixed. I don't think I seriously need to make a rule for that.

**Comment by Shnupbups** [comment]
Further comment on whether this gets reverted or not should be on #5 . Again, not gonna actually revert it myself, I've specifically requested others to review it.

**Pull request merged**
